# Generated by Django 3.2.11 on 2022-01-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.FloatField(null=True)),
                ('ha', models.FloatField(null=True)),
                ('tmp', models.FloatField(null=True)),
                ('lux', models.FloatField(null=True)),
                ('tg', models.FloatField(null=True)),
                ('salg', models.FloatField(null=True)),
                ('ecg', models.FloatField(null=True)),
                ('qua', models.FloatField(null=True)),
                ('onf', models.IntegerField(null=True)),
                ('dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
