# Generated by Django 3.2.11 on 2022-01-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='sm',
            field=models.IntegerField(null=True),
        ),
    ]
