# Generated by Django 3.2.11 on 2022-02-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0003_don_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='ecg',
        ),
        migrations.RemoveField(
            model_name='don',
            name='salg',
        ),
    ]
